[jellyfin-plugin-sso]
src.github = "Buco7854/jellyfin-plugin-sso"
fetch.tarball = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v$ver/sso-authentication_$ver.zip"
src.prefix = "v"

[jellyfin-plugin-sso-src]
src.github = "Buco7854/jellyfin-plugin-sso"
fetch.github = "Buco7854/jellyfin-plugin-sso"

[clair-obscur-fix]
src.webpage = "https://codeberg.org/Lyall/ClairObscurFix/releases"
src.regex = "ClairObscurFix_([0-9.]+)\\.zip"
fetch.tarball = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/$ver/ClairObscurFix_$ver.zip"

[bbdown-linux-x64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-x64.zip"

[bbdown-linux-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-arm64.zip"

[bbdown-osx-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_osx-arm64.zip"

[firefox-csshacks]
src.git = "https://github.com/MrOtherGuy/firefox-csshacks.git"
fetch.git = "https://github.com/MrOtherGuy/firefox-csshacks.git"

[go-fast-note-sync]
src.github = "erichll/go-fast-note-sync"
fetch.github = "erichll/go-fast-note-sync"

[noname]
src.github = "libnoname/noname"
fetch.github = "libnoname/noname"

[rime-cantonese]
src.github = "rime/rime-cantonese"
fetch.github = "rime/rime-cantonese"

[rime-dieghv]
src.git = "https://github.com/kahaani/dieghv.git"
fetch.git = "https://github.com/kahaani/dieghv.git"

[rime-latex]
src.git = "https://github.com/shenlebantongying/rime_latex.git"
fetch.git = "https://github.com/shenlebantongying/rime_latex.git"
