[jellyfin-plugin-sso]
src.github = "Buco7854/jellyfin-plugin-sso"
fetch.tarball = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v$ver/sso-authentication_$ver.zip"
src.prefix = "v"

[jellyfin-plugin-sso-src]
src.github = "Buco7854/jellyfin-plugin-sso"
fetch.github = "Buco7854/jellyfin-plugin-sso"

[clair-obscur-fix]
src.webpage = "https://codeberg.org/Lyall/ClairObscurFix/releases"
src.regex = "ClairObscurFix_([0-9.]+)\\.zip"
fetch.tarball = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/$ver/ClairObscurFix_$ver.zip"

[bbdown-linux-x64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-x64.zip"

[bbdown-linux-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-arm64.zip"

[bbdown-osx-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_osx-arm64.zip"

[firefox-csshacks]
src.git = "https://github.com/MrOtherGuy/firefox-csshacks.git"
fetch.git = "https://github.com/MrOtherGuy/firefox-csshacks.git"

[mpv-bilibili-sponsorblock]
src.github_tag = "test482/mpv-bilibili-sponsorblock"
fetch.github = "test482/mpv-bilibili-sponsorblock"

[go-fast-note-sync]
src.github = "erichll/go-fast-note-sync"
fetch.github = "erichll/go-fast-note-sync"

[oroot]
src.git = "https://github.com/js0ny/oroot.git"
fetch.git = "https://github.com/js0ny/oroot.git"

[limes]
src.git = "https://github.com/js0ny/limes.git"
fetch.git = "https://github.com/js0ny/limes.git"

[noname]
src.github = "libnoname/noname"
fetch.github = "libnoname/noname"

[ratune]
src.github = "acmagn/ratune"
fetch.github = "acmagn/ratune"

[rime-cantonese]
src.github = "rime/rime-cantonese"
fetch.github = "rime/rime-cantonese"

[rime-dieghv]
src.git = "https://github.com/kahaani/dieghv.git"
fetch.git = "https://github.com/kahaani/dieghv.git"

[rime-latex]
src.git = "https://github.com/shenlebantongying/rime_latex.git"
fetch.git = "https://github.com/shenlebantongying/rime_latex.git"

[rime-wanxiang-zrm]
src.github = "amzxyz/rime_wanxiang"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/$ver/rime-wanxiang-zrm-fuzhu.zip"

[rime-wanxiang-flypy]
src.github = "amzxyz/rime_wanxiang"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/$ver/rime-wanxiang-flypy-fuzhu.zip"

[dwproton]
src.cmd = "curl -sSL https://dawn.wine/api/v1/repos/dawn-winery/dwproton/releases/latest | jq -r .tag_name"
fetch.tarball = "https://dawn.wine/dawn-winery/dwproton/releases/download/$ver/$ver-x86_64.tar.xz"

[sts2-Quick-Restart]
src.github = "erasels/StS2-Quick-Restart"
fetch.tarball = "https://github.com/erasels/StS2-Quick-Restart/releases/download/$ver/QuickRestart.zip"

[SlayTheSpire2-LAN-Multiplayer]
src.github = "kmyuhkyuk/SlayTheSpire2.LAN.Multiplayer"
fetch.url = "https://github.com/kmyuhkyuk/SlayTheSpire2.LAN.Multiplayer/releases/download/$ver/SlayTheSpire2.LAN.Multiplayer.Release_$ver.7z"

[dump-tabs]
src.git = "https://github.com/js0ny/dump-tabs.yazi.git"
fetch.git = "https://github.com/js0ny/dump-tabs.yazi.git"

[wdotool]
src.github = "cushycush/wdotool"
fetch.github =  "cushycush/wdotool"

[udpxy]
src.github_tag = "pcherenkov/udpxy"
fetch.github = "pcherenkov/udpxy"

[msd_lite]
src.git = "https://github.com/rozhuk-im/msd_lite.git"
fetch.github = "rozhuk-im/msd_lite"
git.fetchSubmodules = true
