# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  SlayTheSpire2-LAN-Multiplayer = {
    pname = "SlayTheSpire2-LAN-Multiplayer";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/kmyuhkyuk/SlayTheSpire2.LAN.Multiplayer/releases/download/1.6.3/SlayTheSpire2.LAN.Multiplayer.Release_1.6.3.7z";
      sha256 = "sha256-rpoRw6jOU9tuj63gjrHtXgW4TzVH0cH/N10pEBjrb7o=";
    };
  };
  bbdown-linux-arm64 = {
    pname = "bbdown-linux-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-arm64.zip";
      sha256 = "sha256-9Y4KGN8aWJN1QooK8n6mH1zpb/r2fRFfM11fm+6aNNw=";
    };
  };
  bbdown-linux-x64 = {
    pname = "bbdown-linux-x64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-x64.zip";
      sha256 = "sha256-7CM7fY1AscxER9rAW+ND9Tp1fcYFdDqICKuqjpfl0Q4=";
    };
  };
  bbdown-osx-arm64 = {
    pname = "bbdown-osx-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_osx-arm64.zip";
      sha256 = "sha256-TfhAFNgYvW3/KzZbhHZFNA6JVcRFD+llaI9Br4mji6o=";
    };
  };
  clair-obscur-fix = {
    pname = "clair-obscur-fix";
    version = "0.0.15";
    src = fetchTarball {
      url = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/0.0.15/ClairObscurFix_0.0.15.zip";
      sha256 = "sha256-lJV+ujiSx/IkjLG5UcA54+3ucNscV2KBwOYnIlUMM2s=";
    };
  };
  dump-tabs = {
    pname = "dump-tabs";
    version = "745e347bcf9a2bec87370a33d4929d07af09f011";
    src = fetchgit {
      url = "https://github.com/js0ny/dump-tabs.yazi.git";
      rev = "745e347bcf9a2bec87370a33d4929d07af09f011";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Etx5LX9TuiGoxLe6eIH6pYM1wXzsqQ/uY6clq/AiusY=";
    };
    date = "2026-07-09";
  };
  dwproton = {
    pname = "dwproton";
    version = "dwproton-11.0-6";
    src = fetchTarball {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-6/dwproton-11.0-6-x86_64.tar.xz";
      sha256 = "sha256-7nj4uEr8FnCWThD4A2iBynfxTFfNeScxMHshEzgN9F4=";
    };
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "e7b748bfa4572ddcc50cced16a524f5f75dc04f2";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks.git";
      rev = "e7b748bfa4572ddcc50cced16a524f5f75dc04f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KTjiWPp/KUY99rff5gws+s6T8oC1o9a+Eqp+aKlrCWE=";
    };
    date = "2026-06-24";
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-wgtzH5NdkzjXfYUIk9xvugv+QUTWxvlkhor6kkBYZsc=";
    };
  };
  jellyfin-plugin-sso = {
    pname = "jellyfin-plugin-sso";
    version = "4.0.0.6";
    src = fetchTarball {
      url = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v4.0.0.6/sso-authentication_4.0.0.6.zip";
      sha256 = "sha256-U7TA16j8ovPa7zhSDGskb1fuU2Icm4J7EJCCdcUmp+Q=";
    };
  };
  jellyfin-plugin-sso-src = {
    pname = "jellyfin-plugin-sso-src";
    version = "v4.0.0.6";
    src = fetchFromGitHub {
      owner = "Buco7854";
      repo = "jellyfin-plugin-sso";
      rev = "v4.0.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PgDjXTrMCpTKth/nVczBHUCAuaGn8ZWbTXY5yVH5A6M=";
    };
  };
  limes = {
    pname = "limes";
    version = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
    src = fetchgit {
      url = "https://github.com/js0ny/limes.git";
      rev = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nt/y2H5+T9mA0Lvv23dig4BZUUGib16tPiCb0+Fg14Q=";
    };
    date = "2026-07-07";
  };
  mpv-bilibili-sponsorblock = {
    pname = "mpv-bilibili-sponsorblock";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "test482";
      repo = "mpv-bilibili-sponsorblock";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-W3H/mHmXIdmfH8k2wFXfalF4W7WDQIDAW0wo11n3V04=";
    };
  };
  noname = {
    pname = "noname";
    version = "v1.11.4.1";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-Ez/XZHtEDvLCVnJvqxQcUeiZI6GiJMjrorV48eSmbqM=";
    };
  };
  oroot = {
    pname = "oroot";
    version = "0b76c1e834cea24cad8e8ad7204db01f970303ce";
    src = fetchgit {
      url = "https://github.com/js0ny/oroot.git";
      rev = "0b76c1e834cea24cad8e8ad7204db01f970303ce";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-irYbVLJAvf1QooFBJCj1QquO9fNyU3rMoR5eZ/KItz0=";
    };
    date = "2026-07-09";
  };
  ratune = {
    pname = "ratune";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "acmagn";
      repo = "ratune";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-bavGTCOoVcI4LTnnPOalu19YN+5qIYVcKkVjPAIsuzM=";
    };
  };
  rime-cantonese = {
    pname = "rime-cantonese";
    version = "latest";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-cantonese";
      rev = "latest";
      fetchSubmodules = false;
      sha256 = "sha256-M2zFuhKAmSJ3X7zP0+itakhmuHqwtxZVOHS/fn+NSZo=";
    };
  };
  rime-dieghv = {
    pname = "rime-dieghv";
    version = "1709bb786a144de7be2229755011fde9034457de";
    src = fetchgit {
      url = "https://github.com/kahaani/dieghv.git";
      rev = "1709bb786a144de7be2229755011fde9034457de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMViEO0nxNEjVZbHwB0e9vSpe5TfHV7CuJoouS84Pjg=";
    };
    date = "2019-02-11";
  };
  rime-latex = {
    pname = "rime-latex";
    version = "858f2abc645f0e459e468e98122470ce20b16b30";
    src = fetchgit {
      url = "https://github.com/shenlebantongying/rime_latex.git";
      rev = "858f2abc645f0e459e468e98122470ce20b16b30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i8Rgze+tQhbE+nl+JSj09ILXeUvf6MOS9Eqsuqis1n0=";
    };
    date = "2025-04-03";
  };
  rime-wanxiang-flypy = {
    pname = "rime-wanxiang-flypy";
    version = "v16.1.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v16.1.0/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-8Cagd5K/SgxvVxbFjJBuEr3SYaGMTDbFdtNk2shGzs4=";
    };
  };
  rime-wanxiang-zrm = {
    pname = "rime-wanxiang-zrm";
    version = "v16.1.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v16.1.0/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-OVQygGw/KO09xYtPAJk8Y+j/uAqxKeKmuN2lLRcqC44=";
    };
  };
  sts2-Quick-Restart = {
    pname = "sts2-Quick-Restart";
    version = "v1.2.1";
    src = fetchTarball {
      url = "https://github.com/erasels/StS2-Quick-Restart/releases/download/v1.2.1/QuickRestart.zip";
      sha256 = "sha256-lELAlIGxm06jRmNYjfH4Fz5TBbShMd+bwYiUc15xr+Q=";
    };
  };
}
