# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bbdown-linux-arm64 = {
    pname = "bbdown-linux-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-arm64.zip";
      sha256 = "sha256-9Y4KGN8aWJN1QooK8n6mH1zpb/r2fRFfM11fm+6aNNw=";
    };
  };
  bbdown-linux-x64 = {
    pname = "bbdown-linux-x64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-x64.zip";
      sha256 = "sha256-7CM7fY1AscxER9rAW+ND9Tp1fcYFdDqICKuqjpfl0Q4=";
    };
  };
  bbdown-osx-arm64 = {
    pname = "bbdown-osx-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_osx-arm64.zip";
      sha256 = "sha256-TfhAFNgYvW3/KzZbhHZFNA6JVcRFD+llaI9Br4mji6o=";
    };
  };
  clair-obscur-fix = {
    pname = "clair-obscur-fix";
    version = "0.0.15";
    src = fetchTarball {
      url = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/0.0.15/ClairObscurFix_0.0.15.zip";
      sha256 = "sha256-lJV+ujiSx/IkjLG5UcA54+3ucNscV2KBwOYnIlUMM2s=";
    };
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "f460dc79bedcb5cd077dfb8e14e9d46e1881c0e3";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks.git";
      rev = "f460dc79bedcb5cd077dfb8e14e9d46e1881c0e3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EouTytS0ji/R7AfPsjhwGaMONmlxVpXCJIyPNpC7tOs=";
    };
    date = "2026-05-31";
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-wgtzH5NdkzjXfYUIk9xvugv+QUTWxvlkhor6kkBYZsc=";
    };
  };
  jellyfin-plugin-sso = {
    pname = "jellyfin-plugin-sso";
    version = "4.0.0.6";
    src = fetchTarball {
      url = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v4.0.0.6/sso-authentication_4.0.0.6.zip";
      sha256 = "sha256-U7TA16j8ovPa7zhSDGskb1fuU2Icm4J7EJCCdcUmp+Q=";
    };
  };
  jellyfin-plugin-sso-src = {
    pname = "jellyfin-plugin-sso-src";
    version = "v4.0.0.6";
    src = fetchFromGitHub {
      owner = "Buco7854";
      repo = "jellyfin-plugin-sso";
      rev = "v4.0.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PgDjXTrMCpTKth/nVczBHUCAuaGn8ZWbTXY5yVH5A6M=";
    };
  };
}
